/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;


import DomainModels.BaoHanh;
import Repositories.BaoHanhRepository;
import Services.BaoHanhServicee;
import Services.impl.BaoHanhServiceeImpl;
import Utilities.HibernateUtil;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.hibernate.Session;

/**
 *
 * @author PC
 */
public class BaoHanhView extends javax.swing.JFrame {
  private BaoHanhRepository bhrepostority = new BaoHanhRepository();
    private DefaultTableModel defaultTableModel;
    private DefaultComboBoxModel defaultComboBoxModel;
    BaoHanhServicee bhsv = new BaoHanhServiceeImpl();
    private  ArrayList<BaoHanh> list  = new ArrayList<>();
    private List<BaoHanh> listbh = bhrepostority.getAll();
 

    /**
     * Creates new form SizeView
     */
    
    public BaoHanhView() {
        initComponents();
       
        setTitle("Hệ Thống Quản Lý  Bán Giày TTN ");
        loadtable(listbh);
    }
      public void loadtable(List<BaoHanh> list) {
        defaultTableModel = (DefaultTableModel) tblbaoHanh.getModel();
        defaultTableModel.setRowCount(0);
        for (BaoHanh baohanh : list) {
            defaultTableModel.addRow(new Object[]{
                baohanh.getId(),
                baohanh.getMa(),
                baohanh.getTen(),
                baohanh.getTrangThai()
               });
        }
    }
    private Map<String, Object> mapMa = new HashMap<>();
      public boolean checkDL() {
        String p_ten = "[a-zA-Z0-9]+";
        if (txtMa.getText().equals("")) {
            txtMa.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Mã loại sản phẩm không được trống");
            return false;
        } else if (txtMa.getText().matches(p_ten) == false) {
            txtMa.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Mã loại sản phẩm không đúng định dạng");
            return false;
        }
      
          
        
          BaoHanh bh = new BaoHanh();
        if (mapMa.containsKey(bh.getMa())) {
            txtMa.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Mã loại sản phâm bị trùng");
            return false;
        }

        return true;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbbTrangthai = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbaoHanh = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        btnXuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Bảo Hành");

        jLabel5.setText("Trạng thái");

        jLabel2.setText("ID");

        cbbTrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Con Bao Hanh", "Het Bao Hanh" }));

        jLabel3.setText("Mã");

        jLabel4.setText("Ten");

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        tblbaoHanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Mã", "Size", "Trạng thái"
            }
        ));
        tblbaoHanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbaoHanhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbaoHanh);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        txtid.setEditable(false);
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        btnXuat.setText("Xuất ");
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(438, 438, 438))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnThem)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTen)
                                    .addComponent(txtMa)
                                    .addComponent(txtid)
                                    .addComponent(cbbTrangthai, 0, 316, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(btnSua)
                                .addGap(108, 108, 108)
                                .addComponent(btnXoa)
                                .addGap(18, 18, 18)
                                .addComponent(btnXuat))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbTrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnXuat))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(768, 768, 768)
                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblID)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
    String ma = (txtMa.getText());
        String result = bhsv.delete(ma);
        JOptionPane.showMessageDialog(this, result);
        loadtable(bhsv.getALL());
      
    }//GEN-LAST:event_btnXoaActionPerformed
    
    private void tblbaoHanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbaoHanhMouseClicked
     
    }//GEN-LAST:event_tblbaoHanhMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
    if (checkDL()) {

            BaoHanh bh = new BaoHanh();
            bh.setMa(txtMa.getText());
            bh.setTen(txtTen.getText());
           int trangthai = cbbTrangthai .getSelectedIndex();
          
           bh.setTrangThai(trangthai);
//            java.sql.Date ngayt = new java.sql.Date(new java.util.Date().getTime());
//           mausac.setNgayTao(ngayt);

            String result = bhrepostority.add(bh);
            JOptionPane.showMessageDialog(this, result);
            loadtable(bhrepostority.getAll());
        }
      
        
        

    }//GEN-LAST:event_btnThemActionPerformed
    
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed

      

    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
        // TODO add your handling code here:
//        try{
//            XSSFWorkbook wordkbook = new XSSFWorkbook();
//            XSSFSheet sheet = wordkbook.createSheet("BaoHanh");
//            XSSFRow row = null ; 
//            Cell cell = null ; 
//           row = sheet.createRow(4);
//            cell = row.createCell(0,CellType.STRING); // set ten cot trong excel
//            cell.setCellValue("STT");
//           
//            cell = row.createCell(1,CellType.STRING); // set ten cot trong excel
//          cell.setCellValue("ID");
//           cell = row.createCell(2,CellType.STRING); // set ten cot trong excel
//            cell.setCellValue("Mã Bảo Hành");
//            
//            cell = row.createCell(3,CellType.STRING); // set ten cot trong excel
//            cell.setCellValue("Tên Bảo Hành");
//           
//            cell = row.createCell(4,CellType.STRING); // set ten cot trong excel
//            cell.setCellValue("Trạng Thái Bảo Hành");
//           
//             for( int i= 0 ; i< list.size(); i++){
//             row = sheet.createRow(5+i);
//              cell = row.createCell(0 , CellType.NUMERIC);
//              cell.setCellValue(i+1);
//                cell = row.createCell(1 , CellType.STRING);
//              cell.setCellValue(list.get(i).getId()+"");
//                cell = row.createCell(2 , CellType.STRING);
//              cell.setCellValue(list.get(i).getTen());
//                cell = row.createCell(3 , CellType.STRING);
//              cell.setCellValue(list.get(i).getMa());
//                cell = row.createCell(4 , CellType.STRING);
//              cell.setCellValue(list.get(i).getTrangThai());
//        }
//             File f = new File("D:\\Cao Dang FPT\\Java\\DuAn1\\FileExcel");
//             try{
//                 FileOutputStream fis = new FileOutputStream(f);
//                 wordkbook.write(fis);
//                 fis.close();
//             }catch(FileNotFoundException ex){
//                 ex.printStackTrace();
//             }
//             
//            
//        }catch(IOException ex){
//                 ex.printStackTrace();
//             }

    }//GEN-LAST:event_btnXuatActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaoHanhView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaoHanhView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaoHanhView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaoHanhView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaoHanhView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuat;
    private javax.swing.JComboBox<String> cbbTrangthai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JTable tblbaoHanh;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
