/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;


import DomainModels.SanPham;
import Services.SanPhamService;
import Services.impl.SanPhamImpl;
import java.awt.Color;
import java.text.SimpleDateFormat;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class SanPhamView extends javax.swing.JFrame {
private DefaultTableModel dtm = new DefaultTableModel();
private  DefaultComboBoxModel dcm = new DefaultComboBoxModel();
    private DefaultTableModel model = new DefaultTableModel();
    List<SanPham> listSz = new ArrayList<>();
        SanPhamService ssv = new SanPhamImpl();

    /**
     * Creates new form SizeView
     */
    public SanPhamView() {
        initComponents();
        loadTable();
        setTitle("Hệ Thống Quản Lý Cửa Hàng Bán Giày FPT");
        txtid.disable();
      table();
      cbx();
    }
      private void table() {
          tblSize.setModel(dtm);
        Object[] columns = new Object[]{
            "ID", "Mã Sản Phẩm", "Tên Sản Phẩm ", "Trạng Thái"
        };
        dtm.setColumnIdentifiers(columns);
        showData(ssv.getAll());

    }
       private void cbx() {
        cbbTrangthai.removeAllItems();
        dcm.addElement("Còn Hàng");
        dcm.addElement("Hết Hàng");
        cbbTrangthai.setModel(dcm);
        cbbTrangthai.getModel();

    }
    public void showData(List<SanPham> list) {
        dtm.setRowCount(0);
        for (SanPham baoHanh : list) {
            dtm.addRow(new Object[]{
               baoHanh.getId(),baoHanh.getMa(),
                baoHanh.getTen(),
                
                baoHanh.trangThai()
               
                        
            });
        }
    }
     private Map<String, Object> mapMa = new HashMap<>();

    public boolean checkDL() {
        String p_ten = "[a-zA-Z0-9]+";
        if (txtMa.getText().equals("")) {
            txtMa.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Mã loại sản phẩm không được trống");
            return false;
        } else if (txtMa.getText().matches(p_ten) == false) {
            txtMa.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Mã loại sản phẩm không đúng định dạng");
            return false;
        }
        if (txtTen.getText().equals("")) {
            txtTen.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Tên loại sản phẩm không được trống");
            return false;
        } else if (txtTen.getText().matches(p_ten) == false) {
            txtTen.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Tên loại sản phẩm sai định dạng");
            return false;
        }
      

        return true;
    }
     private void fillData(int index) {
        SanPham sp = ssv.getAll().get(index);
        txtMa.setText(sp.getMa());
        txtTen.setText(sp.getTen());
        cbbTrangthai.setSelectedIndex(sp.getTrangThai());
        txtid.setText(sp.getId()+"");
        txtid.disable();

    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbbTrangthai = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSize = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Sản Phẩm");

        jLabel5.setText("Trạng thái");

        jLabel2.setText("ID");

        jLabel3.setText("Mã");

        jLabel4.setText("Ten");

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        tblSize.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", ""
            }
        ));
        tblSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSizeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSize);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTen)
                            .addComponent(txtMa)
                            .addComponent(txtid)
                            .addComponent(cbbTrangthai, 0, 316, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btnThem)
                        .addGap(136, 136, 136)
                        .addComponent(btnSua)
                        .addGap(111, 111, 111)
                        .addComponent(btnXoa)))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(438, 438, 438))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbTrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addGap(82, 82, 82)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(768, 768, 768)
                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblID)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tblSize.getSelectedRow();
        if (row >= 0) {
            JOptionPane.showMessageDialog(this, ssv.delete(txtMa.getText()));
            listSz = ssv.getAll();
            loadTable();
            table();

        } else {
            JOptionPane.showMessageDialog(this, "Chọn hàng cần xóa !");
        }
    }//GEN-LAST:event_btnXoaActionPerformed
    private void loadTable() {
        model.setRowCount(0);
        for (SanPham sp : listSz) {
            model.addRow(new Object[]{sp.getId(), sp.getMa(), sp.getTen(), sp.trangThai()});
        }
    }
    private void tblSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSizeMouseClicked
        //       int row=tblSize.getSelectedRow();
        //       txtMa.setText(tblSize.getValueAt(row,1).toString());
        //       txtSize.setText(tblSize.getValueAt(row,2).toString());
        //       cbbTrangthai.getModel().setSelectedItem(tblSize.getValueAt(row,3).toString());
        //       txtNgayTao.setText(tblSize.getValueAt(row,4).toString());
        //
        //lblID.setText(tblSize.getValueAt(row, 0).toString());
        //        if (!tblSize.getValueAt(row,5).toString().isBlank()) {
        //            txtNgaySua.setText(tblSize.getValueAt(row, 5).toString());
        //        }else{
        //
        //        }
        int row = tblSize.getSelectedRow();
        fillData(row);
    }//GEN-LAST:event_tblSizeMouseClicked
 
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
//
//     SanPham sp = new SanPham();
//
//        sp.setMa(txtMa.getText());
//        sp.setTen(txtTen.getText());
//        
//        
//      int trangthai =0;
//        if (cbbTrangthai.equals("Hết Hàng")) {
//            trangthai = 0;
//        }else if(cbbTrangthai.equals("Còn Hàng")){
//            trangthai = 1;
//        }
//
//        sp.setTrangThai(trangthai);
//     
//        System.out.println("Trang Thai" + trangthai);
//
//     
//           String result = ssv.add(sp);
//        JOptionPane.showMessageDialog(this, result);
//        showData(ssv.getAll());
    if (checkDL()) {
            SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
            SanPham mausac = new SanPham();
            mausac.setMa(txtMa.getText());
            mausac.setTen(txtTen.getText());
            
            mausac.setTrangThai(cbbTrangthai.getSelectedIndex());
         
            String result = ssv.add(mausac);
            JOptionPane.showMessageDialog(this, result);
            showData(ssv.getAll());
        }
  
    }//GEN-LAST:event_btnThemActionPerformed
 
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed

       if (checkDL()) {
            int r = tblSize.getSelectedRow();
          
            SanPham sp = new SanPham();
            sp.setMa(txtMa.getText());
            sp.setTen(txtTen.getText());
            sp.setTrangThai(cbbTrangthai.getSelectedIndex());
         
            String result = ssv.update(sp);
            JOptionPane.showMessageDialog(this, result);

        }
                      showData(ssv.getAll());

    }//GEN-LAST:event_btnSuaActionPerformed
  

   

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPhamView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbTrangthai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JTable tblSize;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
